### ISSUE TITLE
Stopped working (Feb 17)..

### ISSUE THREAD

**Issue by arneelof** [plexinc-plugins/SVT-Play.bundle#68]
I just get "This channel is not responding" since today (Feb 23 2017)...

**Comment by sander1** [comment]
The channel has been updated on Feb 23. I cannot replicate the issue, the updated channel works as expected. Can you provide the `com.plexapp.plugins.svtplay.log` log file please? @meriko or I can probably look into this, but we need something to go on.

**Comment by arneelof** [comment]
Thanks for you help.

This is the error I get:


--
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b46e0ea/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 951, in construct_response

    el = result._to_xml()

  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b46e0ea/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/objectkit.py", line 667, in _to_xml

  el = Framework.modelling.objects.ModelInterfaceObjectContainer._to_xml(self)

  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b46e0ea/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/modelling/objects.py", line 382, in _to_xml

    root = Container._to_xml(self)

  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b46e0ea/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/modelling/objects.py", line 139, in _to_xml

    self._append_children(root, self._objects)

  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b46e0ea/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/modelling/objects.py", line 145, in _append_children

    el = obj._to_xml()

  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b46e0ea/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/objectkit.py", line 580, in _to_xml

    if self._core.services.function_in_service_is_deferred(Framework.components.services.MEDIA_OBJECTS_FUNCTION_NAME, service):

  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b46e0ea/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/services.py", line 557, in function_in_service_is_deferred

    service.sandbox.context.import_values(values)

AttributeError: 'NoneType' object has no attribute 'sandbox

----

For some reason it seems like my SVT-bundle repository does not get updates (check syslog) but according to git it is up to date... Perhaps I am using the wrong repository ?

> git clone https://github.com/plexinc-plugins/SVT-Play.bundle
> git log
commit 5ab9dd6f336d78729722670da967fd6d4cefa453

Merge: 5c9e8b6 da08765

Author: Sander Spies <sander1@users.noreply.github.com>

Date:   Wed Feb 22 20:41:02 2017 +0100



    Merge pull request #67 from meriko/new_api

    

    Fix for broken channel



commit da08765f8b935d9adc06fa516b47aebe877a8ef6

Author: unknown (author) <meriko@hotmail.com>

Date:   Wed Feb 22 19:34:35 2017 +0100



    Fix for broken channel





 
Yours

Arne

**Comment by arneelof** [comment]
Thanks for you help.

This is the error I get:


--

  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b46e0ea/
Framework.bundle/Contents/Resources/Versions/2/Python/
Framework/components/runtime.py", line 951, in construct_response

    el = result._to_xml()

  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b46e0ea/
Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/objectkit.py",
line 667, in _to_xml

  el = Framework.modelling.objects.ModelInterfaceObjectContainer.
_to_xml(self)

  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b46e0ea/
Framework.bundle/Contents/Resources/Versions/2/Python/
Framework/modelling/objects.py", line 382, in _to_xml

    root = Container._to_xml(self)

  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b46e0ea/
Framework.bundle/Contents/Resources/Versions/2/Python/
Framework/modelling/objects.py", line 139, in _to_xml

    self._append_children(root, self._objects)

  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b46e0ea/
Framework.bundle/Contents/Resources/Versions/2/Python/
Framework/modelling/objects.py", line 145, in _append_children

    el = obj._to_xml()

  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b46e0ea/
Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/objectkit.py",
line 580, in _to_xml

    if self._core.services.function_in_service_is_deferred(
Framework.components.services.MEDIA_OBJECTS_FUNCTION_NAME, service):

  File "/usr/lib/plexmediaserver/Resources/Plug-ins-b46e0ea/
Framework.bundle/Contents/Resources/Versions/2/Python/
Framework/components/services.py", line 557, in function_in_service_is_
deferred

    service.sandbox.context.import_values(values)

AttributeError: 'NoneType' object has no attribute 'sandbox
----

For some reason it seems like my SVT-bundle repository does not get updates
(check syslog) but according to git it is up to date... Perhaps I am using
the wrong repository ?

> git clone https://github.com/plexinc-plugins/SVT-Play.bundle
> git log

commit 5ab9dd6f336d78729722670da967fd6d4cefa453

Merge: 5c9e8b6 da08765

Author: Sander Spies <sander1@users.noreply.github.com>

Date:   Wed Feb 22 20:41:02 2017 +0100


    Merge pull request #67 from meriko/new_api



    Fix for broken channel


commit da08765f8b935d9adc06fa516b47aebe877a8ef6

Author: unknown (author) <meriko@hotmail.com>

Date:   Wed Feb 22 19:34:35 2017 +0100


    Fix for broken channel





Yours

Arne


Yours

Arne

-----------------------------------------
  Arne Elofsson                  Science for Life Laboratory
  Tel:+46-(0)70 695 1045   Stockholm University
  http://bioinfo.se/               Box 1031,
  Email: arne@bioinfo.se   17121 Solna, Sweden
  Twitter:   https://twitter.com/arneelof
  Scholar: http://scholar.google.se/citations?user=s3OCM3AAAAAJ
  ORCID: 0000-0002-7115-9751

**Comment by meriko** [comment]
Still hard to say what could be the problem. If you could try the following it would help narrowing it a bit:
1. Restart Plex Media Server
2. Try to play a video
3. Upload the following logs: com.plexapp.system.log, com.plexapp.plugins.svtplay.log(see https://support.plex.tv/hc/en-us/articles/201106098-How-do-I-find-the-Plug-Ins-folder- for a guide)

**Comment by arneelof** [comment]
Thanks again

Before posting I obviously did (a fresh git clone, a reboot, tried access
from different clients  etc....). Other channels and local content works
fine...


I'm away due a week without ssh access to the server. , I'll try digging in
to it when I'm back

Thanks again

**Comment by arneelof** [comment]
I managed to get it to work. Seems as there were at least two errors, not really sure what fixed it or why they appeared).

Services.bundle was empty
Wrong owner of SVT-play.bundle (was username and not plex.plex)

I also installed the version from Nov 2016 and it also seems to work..


Thanks for the help

Arne
